### ISSUE TITLE
Allow to include plugins without inlining into ckeditor.js

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckbuilder#19]
Currently all the plugins listed in `<preset>-build-config.js` are inlined into ckeditor.js. The only way to get additional plugins into `ckeditor/plugins` directory, is to put `--all` flag which will include all the plugins.

It would be nice to provide an option to include **just some** plugins, but without inlining them into ckeditor.js.

**Comment by whity** [comment]
Hello,

this would be great, any development here?

thanks.

**Comment by f1ames** [comment]
Hi @whity, this was covered recently in #29.

You can now use `required_plugins` option, like `-r scayt,autolink` which will add plugins to the build in minifed form but not bundled into `ckeditor.js` file.

**Comment by whity** [comment]
Hi @f1ames , great, thank you.
