### ISSUE TITLE
Can you tell the builder to only include certain language files?

### ISSUE THREAD

**Issue by mhopkins-dynactive** [ckeditor/ckbuilder#22]
I have hit the 10k limit on app engine and I am wondering if I can build ckeditor 4 in such a way that it would remove all of the language files except for the default language. 

Is there a buid-config setting I can add that will do that for me?

Thanks

**Comment by mlewand** [comment]
Sorry for late answer.

Yes you can limit the list languages included in a build using the config. You may take a look on [an example configuration in our releases repository](https://github.com/ckeditor/ckeditor-releases/blob/dd8e777dc4806ffa56280378ab047825632ef1df/build-config.js).

On the other hand langs are loaded dynamically, so I don't see a strong reason to limit their number.

**Comment by mhopkins-dynactive** [comment]
The reason why is because we are using appengine and they have 10k file limit. the language files are 1 file per language per plugin. since we are only using 1 language I will save a lot of files.
