### ISSUE TITLE
Update license blocks produced by the builder

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckbuilder#23]
Currently the builder produces old license headers, e.g. for 4.8.0 file `lang/af.js` has a following license block:

```js
/*
Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
For licensing, see LICENSE.md or http://ckeditor.com/license
*/
```

Same thing goes to minified file, like `ckeditor.js`.

It was added in ckeditor/ckeditor-dev#1203.

**Comment by wwalc** [comment]
This issues was supposed to be fixed by f7cd902441a509f5b87999e2288e8cedee81b888 and has been released in version 2.3.2.
