### ISSUE TITLE
Emojione-Icon is added with the wrong size

### ISSUE THREAD

**Issue by kaljak** [ckeditor/ckbuilder#28]
Problem: Emojione-Icon is not shown in the CKEditor-Toolbar

1. Go to https://ckeditor.com/cke4/builder
2. Choose "basic" and add emojione
3. Download the bundle
--> in plugins/icons.png emojione Icon is way too big

**Comment by f1ames** [comment]
Hello @kaljak,
`Emojione` is 3rd-party plugin not developed by CKSource so you should report this issue to the plugin authors directly (https://github.com/braune-digital/ckeditor-emojione).

You may also check if [official CKEditor 4 Emoji plugin](https://ckeditor.com/cke4/addon/emoji) meets your needs.
